import './globals.css'
import type { Metadata } from 'next'
import { Poppins } from 'next/font/google'
import TopBar from '@/components/shared/TopBar'
import LeftSideBar from '@/components/shared/LeftSideBar'
import RightSidebar from '@/components/shared/RightSideBar'
import BottomBar from '@/components/shared/BottomBar'

const poppins = Poppins({ subsets: ['latin'], weight: [ "600"] })

export const metadata: Metadata = {
  title: 'Bitcoin Trading',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
     <body className={poppins.className}>
        <TopBar />
        <main className='flex flex-row '>
          <LeftSideBar />

          <section className='main-container'>
            <div className='w-full max-w-4xl'>
            {children}
            </div>
          </section>
          <RightSidebar />
        </main>
        <BottomBar />
      </body>
    </html>
  )
}
